#!/bin/sh

# 커밋 메시지 파일 경로
COMMIT_MSG_FILE=$1

# 커밋 메시지 읽기
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# 템플릿 규칙에 맞는지 확인하는 함수
validate_commit_message() {
	message=$1

	# 각 브랜치에 대한 규칙 설정
	case "$BRANCH_TYPE" in
	main)
		if ! echo "$message" | grep -Eq "^v[0-9]+\.[0-9]+\.[0-9]+: .+"; then
			printf "\033[1;31m커밋 메시지가 올바른 형식을 따르지 않습니다.\033[0m\n"
			printf "\033[1;33m'vX.Y.Z: <내용>' 형식을 사용하세요.\033[0m\n"
			exit 1
		fi
		;;
	release)
		if ! echo "$message" | grep -Eq "^release/v[0-9]+\.[0-9]+\.[0-9]+: .+"; then
			printf "\033[1;31m커밋 메시지가 올바른 형식을 따르지 않습니다.\033[0m\n"
			printf "\033[1;33m'release/vX.Y.Z: <내용>' 형식을 사용하세요.\033[0m\n"
			exit 1
		fi
		;;
	hotfix)
		if ! echo "$message" | grep -Eq "^hotfix/[0-9a-zA-Z\_-]+: .+"; then
			printf "\033[1;31m커밋 메시지가 올바른 형식을 따르지 않습니다.\033[0m\n"
			printf "\033[1;33m'hotfix/<id>: <버그 내용>' 형식을 사용하세요.\033[0m\n"
			exit 1
		fi
		;;
	develop)
		if ! echo "$message" | grep -Eq "^develop: .+"; then
			printf "\033[1;31m커밋 메시지가 올바른 형식을 따르지 않습니다.\033[0m\n"
			printf "\033[1;33m'develop: <내용>' 형식을 사용하세요.\033[0m\n"
			exit 1
		fi
		;;
	feature)
		if ! echo "$message" | grep -Eq "^feature/[0-9a-zA-Z\_-]+: .+"; then
			printf "\033[1;31m커밋 메시지가 올바른 형식을 따르지 않습니다.\033[0m\n"
			printf "\033[1;33m'feature/<id>: <내용>' 형식을 사용하세요.\033[0m\n"
			exit 1
		fi
		;;
	*)
		printf "\033[1;31m알 수 없는 브랜치 유형입니다. 브랜치 유형을 확인하세요.\033[0m\n"
		printf "\033[1;33m사용 가능한 브랜치 유형 (main|release/*|hotfix/*|develop|feature/*)\033[0m\n"
		exit 1
		;;
	esac
}

# 브랜치 이름에 따라 브랜치 유형 설정
BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_TYPE=$(echo "$BRANCH_NAME" | cut -d'/' -f1)

# 커밋 메시지 검증
validate_commit_message "$COMMIT_MSG"
