# ?? ??
sonar.projectName=Repo Base
sonar.projectKey=blueriver97_repo-base
sonar.organization=blueriver97
sonar.sourceEncoding=UTF-8

# ?? ??
sonar.sources=.

# ?? ??? ???
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.git/**

# ???? ?? ???? ??
sonar.coverage.exclusions=**/*
