name: CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "배포 환경"
        required: true
        type: choice
        options:
          - dev
          - prod

concurrency:
  group: ${{ github.ref }}-${{ github.event.inputs.environment }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: read

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set project name
        run: echo "PROJECT_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)" >> "$GITHUB_ENV"

      - name: Prepare server
        # workflow_dispatch의 입력값과 matrix의 environment가 일치할 때만 실행
        if: (github.ref == 'refs/heads/develop' && github.event.inputs.environment == 'dev') || github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1
        env:
          USER_NAME: ${{ github.event.inputs.environment == 'dev' && secrets.DEV_USER || secrets.PROD_USER }}
          GROUP_NAME: ${{ github.event.inputs.environment == 'dev' && secrets.DEV_GRUOP || secrets.PROD_GRUOP }}
        with:
          host: ${{ github.event.inputs.environment == 'dev' && secrets.DEV_HOST || secrets.PROD_HOST }}
          username: ${{ github.event.inputs.environment == 'dev' && secrets.DEV_USER || secrets.PROD_USER }}
          key: ${{ github.event.inputs.environment == 'dev' && secrets.DEV_DEPLOY_KEY || secrets.PROD_DEPLOY_KEY }}
          script: |
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S mkdir -p /opt/${{ env.PROJECT_NAME }}
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S chown -R ${{ env.USER_NAME }}:${{ env.GROUP_NAME }} /opt/${{ env.PROJECT_NAME }}

      - name: Rsync deploy
        env:
          SSH_KEY: ${{ github.event.inputs.environment == 'dev' && secrets.DEV_DEPLOY_KEY || secrets.PROD_DEPLOY_KEY }}
          REMOTE_USER: ${{ github.event.inputs.environment == 'dev' && secrets.DEV_USER || secrets.PROD_USER }}
          REMOTE_HOST: ${{ github.event.inputs.environment == 'dev' && secrets.DEV_HOST || secrets.PROD_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          rsync -az --delete -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p 22" ./ \
            $REMOTE_USER@$REMOTE_HOST:/opt/${{ env.PROJECT_NAME }}
