# .github/workflows/cd.yml

name: CD

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "브랜치 선택"
        required: true
        type: choice
        options:
          - develop
          - main
      environment:
        description: "배포 환경"
        required: true
        type: choice
        options:
          - dev
          - prod

concurrency:
  group: ${{ github.event.inputs.branch }}-${{ github.event.inputs.environment }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    # 입력받은 environment 값으로 strategy를 설정합니다.
    # develop branch --> only dev, main branch --> dev, prod
    strategy:
      matrix:
        include:
          - branch: develop
            environment: dev
            host: ${{ secrets.DEV_HOST }}
            user: ${{ secrets.DEV_USER }}
            key: ${{ secrets.DEV_DEPLOY_KEY }}
          - branch: main
            environment: dev
            host: ${{ secrets.DEV_HOST }}
            user: ${{ secrets.DEV_USER }}
            key: ${{ secrets.DEV_DEPLOY_KEY }}
          - branch: main
            environment: prod
            host: ${{ secrets.PROD_HOST }}
            user: ${{ secrets.PROD_USER }}
            key: ${{ secrets.PROD_DEPLOY_KEY }}

    # workflow_dispatch의 입력값과 matrix의 environment가 일치할 때만 실행
    if: github.event.inputs.branch == matrix.branch && github.event.inputs.environment == matrix.environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set project name
        run: echo "PROJECT_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)" >> "$GITHUB_ENV"

      - name: Prepare server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ matrix.host }}
          username: ${{ matrix.user }}
          key: ${{ matrix.key }}
          script: |
            sudo mkdir -p /opt/${{ env.PROJECT_NAME }}
            sudo chown -R ${{ matrix.user }}:${{ matrix.user }} /opt/${{ env.PROJECT_NAME }}

      - name: Deploy code
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -az --delete
          path: ./
          remote_path: /opt/${{ env.PROJECT_NAME }}
          remote_host: ${{ matrix.host }}
          remote_user: ${{ matrix.user }}
          remote_key: ${{ matrix.key }}
