name: CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "배포 환경"
        required: true
        type: choice
        options:
          - dev
          - prod

concurrency:
  group: ${{ github.ref }}-${{ github.event.inputs.environment }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: read

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set project name
        run: echo "PROJECT_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)" >> "$GITHUB_ENV"

      - name: Prepare server
        # workflow_dispatch의 입력값과 matrix의 environment가 일치할 때만 실행
        if: (github.ref == 'ref/heads/develop' && github.event.inputs.environment == 'dev') || github.ref == 'ref/heads/main'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ github.event.inputs.environment == 'dev' && secrets.DEV_HOST || secrets.PROD_HOST }}
          username: ${{ github.event.inputs.environment == 'dev' && secrets.DEV_USER || secrets.PROD_USER }}
          key: ${{ github.event.inputs.environment == 'dev' && secrets.DEV_DEPLOY_KEY || secrets.PROD_DEPLOY_KEY }}
          script: |
            sudo mkdir -p /opt/${{ env.PROJECT_NAME }}
            sudo chown -R ${{ matrix.user }}:${{ matrix.user }} /opt/${{ env.PROJECT_NAME }}

      - name: Deploy code
        if: (github.ref == 'ref/heads/develop' && github.event.inputs.environment == 'dev') || github.ref == 'ref/heads/main'
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -az --delete
          path: ./
          remote_path: /opt/${{ env.PROJECT_NAME }}
          remote_host: ${{ github.event.inputs.environment == 'dev' && secrets.DEV_HOST || secrets.PROD_HOST }}
          remote_user: ${{ github.event.inputs.environment == 'dev' && secrets.DEV_USER || secrets.PROD_USER }}
          remote_key: ${{ github.event.inputs.environment == 'dev' && secrets.DEV_DEPLOY_KEY || secrets.PROD_DEPLOY_KEY }}
